services:
  server:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/containers/test-task
    container_name: test-ba
  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: test-ba-db
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
